### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by b246wang** [b246wang/FocusTime#21]
- [ ] Setup firebase (back end)
  - [ ] Auth: Implement Auth API
  - [ ] Auth: Check if facebook session id needs to be converted to app session id to persist logged-in status, and use this app session id to manage user identity (e.g. fetch tasks)
  - [ ] Database: Implement database and figure out schema (e.g. task group project flag, group member list)
  - [ ] Setup database, confirm which language & format between server and client
  - [ ] Firebase Notification
  - [ ] Task Creation API
  - [ ] Task Add Pomo API
  - [ ] Task Deletion API
  - [ ] Task Finish API
  - [ ] Task List Get API: input `sessionId`, output `taskList` with all ongoing and completed task info needed for front end, preferably 2d list: [[ongoing_tasks], [finished tasks]], default sort tasks by due date (closer due date at the top), and default sort finished tasks by completed date
  - [ ] Logout API
- [ ] UI (front end):
  - [ ] Optional: (investigate a little more) setup material design
  - [ ] Auth: Use Facebook login only, remove user credential.
  - [ ] Task list: Add progress circle
  - [ ] Task list: Entire task block is a button, tap on it to see detail (Checkbox is removed)
  - [ ] Task list: Implement task detail view: See screenshot on d1 doc (Add Finish Task button)
  - [ ] Task list: Pull down task list to refresh task list from server
  - [ ] Task list: Group member initial
  - [ ] Task list detail view: Show finished pomo(s) from each member if it is a group project (see screenshot)
  - [ ] Add new task: Add checkbox for group project
  - [ ] Add new task: If group project, use a text field/dropdown list to add new members (make sure UI design is clear)
  - [ ] Timer: Focus Long onPress 25 mins, short onPress 10 secs
  - [ ] Timer: After focus timer count down, select which task to add pomo in a pop up window
  - [ ] Timer: Break Long onPress 5 mins, short onPress 5 secs
  - [ ] Task History: Copy of Task list item (change `completed` to `actual completed`, add `Finished at`), no need to click on it
  - [ ] Sidebar: Show facebook name, id, profile photo, and logout button (sync with firebase authentication)
